# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
workflows:
  version: 2

  build-approve-deploy:
    jobs:
      - bundle
      - unit-tests:
          requires:
            - bundle
      - go-staging:
          requires:
            - unit-tests
          filters:
            branches:
              only: master

jobs:
  bundle:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1.1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path ./vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1.1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: create database
          command: |
            bundle exec rake db:create
      - run:
          name: load schema
          command: |
            bundle exec rake db:schema:load

  unit-tests:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          CI_BUILD_NAME: units

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1.1-dependencies-
      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Rspec
          command: bundle exec rspec --require spec_helper

  # Staging deploy
  go-staging:
    docker:
      - image: cgswong/aws
    steps:
      - deploy:
          name: Deploy Staging
          command: |
            aws opsworks --region eu-central-1 update-app --app-id ee851199-14d7-4865-84a2-3aca37d042f4 --app-source Revision=$CIRCLE_SHA1
            aws opsworks --region eu-central-1 create-deployment --stack-id c52331b2-f2f2-4892-8d7c-e21c900874eb --app-id ee851199-14d7-4865-84a2-3aca37d042f4 --command "{\"Name\":\"deploy\"}"
